<?php
/**
 * AnalyticsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  API_TurboSMTP_Invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * TurboSMTP Public APIs
 *
 * This document describes all public turboSMTP **V2** API and offers endpoints Descriptions, Parameters, Requests, Responses and Samples of usage.  [Click here to view the previous version of turboSMTP Public API Version 1.0](https://www.serversmtp.com/turbo-api-1)   # Security For the most part (and where not otherwise explicit) turboSMTP’s API requires Authorization.   Authorization to access a user’s resource is granted to clients provided they set  authentication headers into their request, valued with the proper values issued by turboSMTP servers.  ## *  Authorization via ConsumerKey/ConsumerSecret  This type of authorization consists of a pair of headers, named consumerKey and consumerSecret that are created and granted to the end user to be used in a permanent way (unless they´re deleted of course). This kind of authentication is intended to provide access to endpoints features without the need of providing the user the account details (email address + password).  *consumerKey:* Consumer Key Granted.  *consumerSecret:* Consumer Secret Granted.  (Use [/consumerKeys/create](#/consumerkey/createConsumerKey) create a consumer key/secret pair).      ## *  Authorization via Authentication Key  The authentication key is user-based and it is issued by turboSMTP servers upon successful user’s email address + password challenge, performed by means of appropriate request.      *Authorization:* Authorization_Key  (Use [/authentication/authorize](#/authentication/AuthenticationLogin) to obtain an API Key)  # Data Interchange Format  For the most part (and where not otherwise explicit) turboSMTP’s API uses JSON as the data format of choice when it comes to request and response bodies.
 *
 * The version of the OpenAPI document: 2.0.0-oas3
 * Contact: api@turbo-smtp.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace API_TurboSMTP_Invoker\API_TurboSMTP;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use API_TurboSMTP_Invoker\ApiException;
use API_TurboSMTP_Invoker\Configuration;
use API_TurboSMTP_Invoker\HeaderSelector;
use API_TurboSMTP_Invoker\ObjectSerializer;

/**
 * AnalyticsApi Class Doc Comment
 *
 * @category Class
 * @package  API_TurboSMTP_Invoker
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AnalyticsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'exportAnalyticsDataCSV' => [
            'application/json',
        ],
        'getAnalyticsData' => [
            'application/json',
        ],
        'getAnalyticsDataByID' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation exportAnalyticsDataCSV
     *
     * Export Analytics data in CSV file
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportAnalyticsDataCSV'] to see the possible values for this operation
     *
     * @throws \API_TurboSMTP_Invoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return string|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError
     */
    public function exportAnalyticsDataCSV($from, $to, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['exportAnalyticsDataCSV'][0])
    {
        list($response) = $this->exportAnalyticsDataCSVWithHttpInfo($from, $to, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType);
        return $response;
    }

    /**
     * Operation exportAnalyticsDataCSVWithHttpInfo
     *
     * Export Analytics data in CSV file
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportAnalyticsDataCSV'] to see the possible values for this operation
     *
     * @throws \API_TurboSMTP_Invoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of string|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function exportAnalyticsDataCSVWithHttpInfo($from, $to, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['exportAnalyticsDataCSV'][0])
    {
        $request = $this->exportAnalyticsDataCSVRequest($from, $to, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation exportAnalyticsDataCSVAsync
     *
     * Export Analytics data in CSV file
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportAnalyticsDataCSV'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exportAnalyticsDataCSVAsync($from, $to, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['exportAnalyticsDataCSV'][0])
    {
        return $this->exportAnalyticsDataCSVAsyncWithHttpInfo($from, $to, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation exportAnalyticsDataCSVAsyncWithHttpInfo
     *
     * Export Analytics data in CSV file
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportAnalyticsDataCSV'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function exportAnalyticsDataCSVAsyncWithHttpInfo($from, $to, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['exportAnalyticsDataCSV'][0])
    {
        $returnType = 'string';
        $request = $this->exportAnalyticsDataCSVRequest($from, $to, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'exportAnalyticsDataCSV'
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['exportAnalyticsDataCSV'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function exportAnalyticsDataCSVRequest($from, $to, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['exportAnalyticsDataCSV'][0])
    {

        // verify the required parameter 'from' is set
        if ($from === null || (is_array($from) && count($from) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from when calling exportAnalyticsDataCSV'
            );
        }

        // verify the required parameter 'to' is set
        if ($to === null || (is_array($to) && count($to) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to when calling exportAnalyticsDataCSV'
            );
        }









        $resourcePath = '/analytics/csv';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status[]', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_by,
            'filter_by', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            'filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $smart_search,
            'smart_search', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderby,
            'orderby', // param base name
            'AnalyticOrderBy', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ordertype,
            'ordertype', // param base name
            'OrderType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tz,
            'tz', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/csv', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('consumerSecret');
        if ($apiKey !== null) {
            $headers['consumerSecret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('consumerKey');
        if ($apiKey !== null) {
            $headers['consumerKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAnalyticsData
     *
     * Get Analytics Data
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  int $page Page number (optional, default to 1)
     * @param  int $limit The numbers of rows per page to return (optional, default to 10)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsData'] to see the possible values for this operation
     *
     * @throws \API_TurboSMTP_Invoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError
     */
    public function getAnalyticsData($from, $to, $page = 1, $limit = 10, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['getAnalyticsData'][0])
    {
        list($response) = $this->getAnalyticsDataWithHttpInfo($from, $to, $page, $limit, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType);
        return $response;
    }

    /**
     * Operation getAnalyticsDataWithHttpInfo
     *
     * Get Analytics Data
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  int $page Page number (optional, default to 1)
     * @param  int $limit The numbers of rows per page to return (optional, default to 10)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsData'] to see the possible values for this operation
     *
     * @throws \API_TurboSMTP_Invoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAnalyticsDataWithHttpInfo($from, $to, $page = 1, $limit = 10, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['getAnalyticsData'][0])
    {
        $request = $this->getAnalyticsDataRequest($from, $to, $page, $limit, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAnalyticsDataAsync
     *
     * Get Analytics Data
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  int $page Page number (optional, default to 1)
     * @param  int $limit The numbers of rows per page to return (optional, default to 10)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAnalyticsDataAsync($from, $to, $page = 1, $limit = 10, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['getAnalyticsData'][0])
    {
        return $this->getAnalyticsDataAsyncWithHttpInfo($from, $to, $page, $limit, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAnalyticsDataAsyncWithHttpInfo
     *
     * Get Analytics Data
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  int $page Page number (optional, default to 1)
     * @param  int $limit The numbers of rows per page to return (optional, default to 10)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAnalyticsDataAsyncWithHttpInfo($from, $to, $page = 1, $limit = 10, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['getAnalyticsData'][0])
    {
        $returnType = '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticsListSucessResponsetBody';
        $request = $this->getAnalyticsDataRequest($from, $to, $page, $limit, $status, $filter_by, $filter, $smart_search, $orderby, $ordertype, $tz, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAnalyticsData'
     *
     * @param  \DateTime $from Start date (required)
     * @param  \DateTime $to End date (required)
     * @param  int $page Page number (optional, default to 1)
     * @param  int $limit The numbers of rows per page to return (optional, default to 10)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailStatus[] $status Filter by Status      NEW: email has been queued for delivery     DEFER: email is in the queue for delivery     SUCCESS: email has been delivered.     OPEN: email has been opened.     CLICK: email has been clicked.     REPORT: email has been reported as spam.     FAIL: email has bounced.     SYSFAIL: email was dropped.     UNSUB: email is unsubscribed.  &lt;br /&gt; Notice that emails that fall into the above statuses can be grouped, ie Turbo-Smtp uses the following groups: &lt;br /&gt;      &#39;Clicks&#39; &#x3D; &#39;CLICK&#39;,     &#39;Unsubscribes&#39; &#x3D; &#39;UNSUB&#39;,     &#39;Spam&#39; &#x3D; &#39;REPORT&#39;,     &#39;Drop&#39; &#x3D; &#39;SYSFAIL&#39;,     &#39;Queued&#39; &#x3D; &#39;NEW&#39; or &#39;DEFER&#39;,     &#39;Opens&#39;&#x3D; &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Delivered&#39;&#x3D; &#39;SUCCESS&#39;  or &#39;OPEN&#39; or &#39;CLICK&#39; or &#39;UNSUB&#39; or &#39;REPORT&#39;,     &#39;Bounce&#39;: &#39;FAIL&#39;. (optional)
     * @param  \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticFilterByOption[] $filter_by Filter by (optional)
     * @param  string $filter Text to search (recipient, sender, email subject or reason for suppression) (optional)
     * @param  bool $smart_search Smart search (optional, default to false)
     * @param  AnalyticOrderBy $orderby Order by (optional)
     * @param  OrderType $ordertype (optional)
     * @param  string $tz Timezone Offset (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAnalyticsDataRequest($from, $to, $page = 1, $limit = 10, $status = null, $filter_by = null, $filter = null, $smart_search = false, $orderby = null, $ordertype = null, $tz = null, string $contentType = self::contentTypes['getAnalyticsData'][0])
    {

        // verify the required parameter 'from' is set
        if ($from === null || (is_array($from) && count($from) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from when calling getAnalyticsData'
            );
        }

        // verify the required parameter 'to' is set
        if ($to === null || (is_array($to) && count($to) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $to when calling getAnalyticsData'
            );
        }

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling AnalyticsApi.getAnalyticsData, must be bigger than or equal to 1.');
        }
        
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling AnalyticsApi.getAnalyticsData, must be bigger than or equal to 1.');
        }
        








        $resourcePath = '/analytics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to,
            'to', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status[]', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter_by,
            'filter_by', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filter,
            'filter', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $smart_search,
            'smart_search', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $orderby,
            'orderby', // param base name
            'AnalyticOrderBy', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ordertype,
            'ordertype', // param base name
            'OrderType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $tz,
            'tz', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('consumerSecret');
        if ($apiKey !== null) {
            $headers['consumerSecret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('consumerKey');
        if ($apiKey !== null) {
            $headers['consumerKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getAnalyticsDataByID
     *
     * Get Analytics Single Item by ID
     *
     * @param  int $id Id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsDataByID'] to see the possible values for this operation
     *
     * @throws \API_TurboSMTP_Invoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonBadRequestResponseBody|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonMessageResponseBody
     */
    public function getAnalyticsDataByID($id, string $contentType = self::contentTypes['getAnalyticsDataByID'][0])
    {
        list($response) = $this->getAnalyticsDataByIDWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getAnalyticsDataByIDWithHttpInfo
     *
     * Get Analytics Single Item by ID
     *
     * @param  int $id Id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsDataByID'] to see the possible values for this operation
     *
     * @throws \API_TurboSMTP_Invoker\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonBadRequestResponseBody|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError|\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonMessageResponseBody, HTTP status code, HTTP response headers (array of strings)
     */
    public function getAnalyticsDataByIDWithHttpInfo($id, string $contentType = self::contentTypes['getAnalyticsDataByID'][0])
    {
        $request = $this->getAnalyticsDataByIDRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonBadRequestResponseBody' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonBadRequestResponseBody' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonBadRequestResponseBody', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonMessageResponseBody' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonMessageResponseBody' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonMessageResponseBody', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonBadRequestResponseBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AuthorizationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\CommonMessageResponseBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getAnalyticsDataByIDAsync
     *
     * Get Analytics Single Item by ID
     *
     * @param  int $id Id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsDataByID'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAnalyticsDataByIDAsync($id, string $contentType = self::contentTypes['getAnalyticsDataByID'][0])
    {
        return $this->getAnalyticsDataByIDAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getAnalyticsDataByIDAsyncWithHttpInfo
     *
     * Get Analytics Single Item by ID
     *
     * @param  int $id Id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsDataByID'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAnalyticsDataByIDAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getAnalyticsDataByID'][0])
    {
        $returnType = '\API_TurboSMTP_Invoker\API_TurboSMTP_Model\AnalyticMailItem';
        $request = $this->getAnalyticsDataByIDRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getAnalyticsDataByID'
     *
     * @param  int $id Id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getAnalyticsDataByID'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getAnalyticsDataByIDRequest($id, string $contentType = self::contentTypes['getAnalyticsDataByID'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getAnalyticsDataByID'
            );
        }


        $resourcePath = '/analytics/{Id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'Id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('consumerSecret');
        if ($apiKey !== null) {
            $headers['consumerSecret'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('consumerKey');
        if ($apiKey !== null) {
            $headers['consumerKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
